!$THEME = "C4_veridas"

' Palette
!$VERIDAS_CORAL_DARK ?= "#FC8F8F"
!$VERIDAS_CORAL_MEDIUM ?= "#FC8F8F"
!$VERIDAS_CORAL_LIGHT ?= "F4D8D5"
!$VERIDAS_BLUE_DARK ?= "#00D44"
!$VERIDAS_WHITE ?= "#F1F0ED"
!$VERIDAS_NEUTRAL_DARK ?= "#424347"
!$VERIDAS_NEUTRAL_MEDIUM ?= "6E6E71"

!$ELEMENT_FONT_COLOR ?= $VERIDAS_WHITE
!$SECONDARY_FONT_COLOR ?= $VERIDAS_BLUE_DARK

!$PERSON_BORDER_COLOR ?= $VERIDAS_BLUE_DARK
!$PERSON_BG_COLOR ?= $VERIDAS_BLUE_DARK
!$PERSON_FONT_COLOR ?= $ELEMENT_FONT_COLOR 
!$EXTERNAL_PERSON_BG_COLOR ?= $VERIDAS_NEUTRAL_DARK 
!$EXTERNAL_PERSON_FONT_COLOR ?= $ELEMENT_FONT_COLOR 
!$EXTERNAL_PERSON_BORDER_COLOR ?= $VERIDAS_NEUTRAL_DARK 

!$SYSTEM_FONT_COLOR ?= $SECONDARY_FONT_COLOR
!$SYSTEM_BG_COLOR ?= $VERIDAS_CORAL_DARK 
!$SYSTEM_BORDER_COLOR ?= $VERIDAS_CORAL_DARK 
!$EXTERNAL_SYSTEM_BG_COLOR ?= $VERIDAS_NEUTRAL_MEDIUM 
!$EXTERNAL_SYSTEM_FONT_COLOR ?= $ELEMENT_FONT_COLOR 
!$EXTERNAL_SYSTEM_BORDER_COLOR ?= $VERIDAS_NEUTRAL_MEDIUM 

' Pending to review

!$CONTAINER_FONT_COLOR ?= $ELEMENT_FONT_COLOR 
!$CONTAINER_BG_COLOR ?= "#438DD5" 
!$CONTAINER_BORDER_COLOR ?= "#3C7FC0" 
!$EXTERNAL_CONTAINER_FONT_COLOR ?= $ELEMENT_FONT_COLOR 
!$EXTERNAL_CONTAINER_BG_COLOR ?= "#B3B3B3" 
!$EXTERNAL_CONTAINER_BORDER_COLOR ?= "#A6A6A6" 

!$COMPONENT_FONT_COLOR ?= "#000000" 
!$COMPONENT_BG_COLOR ?= "#85BBF0" 
!$COMPONENT_BORDER_COLOR ?= "#78A8D8" 
!$EXTERNAL_COMPONENT_FONT_COLOR ?= $COMPONENT_FONT_COLOR 
!$EXTERNAL_COMPONENT_BG_COLOR ?= "#CCCCCC" 
