!$THEME = "C4_veridas"

' Palette
!$VERIDAS_CORAL_DARK ?= "#FC8F8F"
!$VERIDAS_CORAL_MEDIUM ?= "#FC8F8F"
!$VERIDAS_CORAL_LIGHT ?= "#F4D8D5"
!$VERIDAS_BLUE_DARK ?= "#000D44"
!$VERIDAS_WHITE ?= "#F1F0ED"
!$VERIDAS_NEUTRAL_DARK ?= "#424347"
!$VERIDAS_NEUTRAL_MEDIUM ?= "#6E6E71"

' Non defined by ux&ui
!$VERIDAS_NEUTRAL_LIGHT ?= "#B3B3B3"

!$ELEMENT_FONT_COLOR ?= $VERIDAS_WHITE
!$SECONDARY_FONT_COLOR ?= $VERIDAS_BLUE_DARK

!$PERSON_BORDER_COLOR ?= $VERIDAS_BLUE_DARK
!$PERSON_BG_COLOR ?= $VERIDAS_BLUE_DARK
!$PERSON_FONT_COLOR ?= $ELEMENT_FONT_COLOR
!$EXTERNAL_PERSON_BG_COLOR ?= $VERIDAS_NEUTRAL_DARK
!$EXTERNAL_PERSON_FONT_COLOR ?= $ELEMENT_FONT_COLOR
!$EXTERNAL_PERSON_BORDER_COLOR ?= $VERIDAS_NEUTRAL_DARK

!$SYSTEM_FONT_COLOR ?= $SECONDARY_FONT_COLOR
!$SYSTEM_BG_COLOR ?= $VERIDAS_CORAL_DARK
!$SYSTEM_BORDER_COLOR ?= $VERIDAS_CORAL_DARK
!$EXTERNAL_SYSTEM_BG_COLOR ?= $VERIDAS_NEUTRAL_MEDIUM
!$EXTERNAL_SYSTEM_FONT_COLOR ?= $ELEMENT_FONT_COLOR
!$EXTERNAL_SYSTEM_BORDER_COLOR ?= $VERIDAS_NEUTRAL_MEDIUM

!$CONTAINER_FONT_COLOR ?= $SECONDARY_FONT_COLOR
!$CONTAINER_BG_COLOR ?= $VERIDAS_CORAL_MEDIUM
!$CONTAINER_BORDER_COLOR ?= $VERIDAS_CORAL_MEDIUM
!$EXTERNAL_CONTAINER_FONT_COLOR ?= $ELEMENT_FONT_COLOR
!$EXTERNAL_CONTAINER_BG_COLOR ?= $VERIDAS_NEUTRAL_LIGHT
!$EXTERNAL_CONTAINER_BORDER_COLOR ?= $VERIDAS_NEUTRAL_LIGHT

!$COMPONENT_FONT_COLOR ?= $SECONDARY_FONT_COLOR
!$COMPONENT_BG_COLOR ?= $VERIDAS_CORAL_LIGHT
!$COMPONENT_BORDER_COLOR ?= $VERIDAS_CORAL_LIGHT
!$EXTERNAL_COMPONENT_FONT_COLOR ?= $ELEMENT_FONT_COLOR
!$EXTERNAL_COMPONENT_BG_COLOR ?= $EXTERNAL_CONTAINER_BG_COLOR

' "C4 styled" default is that lifeline is arrow color
!$SEQUENCE_BG_COLOR ?= $VERIDAS_BLUE_DARK
!$ARROW_COLOR ?= $VERIDAS_CORAL_DARK
!$BOUNDARY_COLOR ?= $VERIDAS_NEUTRAL_DARK

skinparam SequenceLifelineBorderColor $ARROW_COLOR

skinparam SequenceGroupBodyBackgroundColor $SEQUENCE_BG_COLOR
skinparam SequenceGroupFontColor $BOUNDARY_COLOR
skinparam SequenceGroupBackgroundColor $BOUNDARY_COLOR
skinparam SequenceGroupHeaderFontColor $SEQUENCE_BG_COLOR
skinparam SequenceGroupBorderColor $BOUNDARY_COLOR

skinparam SequenceReferenceBackgroundColor $SEQUENCE_BG_COLOR
skinparam SequenceReferenceFontColor $BOUNDARY_COLOR
skinparam SequenceReferenceHeaderBackgroundColor $BOUNDARY_COLOR
' VIA STYLE
' skinparam SequenceReferenceHeaderFontColor $SEQUENCE_BG_COLOR
<style>
referenceHeader {
  fontcolor $SEQUENCE_BG_COLOR
}
</style>
skinparam SequenceReferenceBorderColor $BOUNDARY_COLOR

skinparam SequenceDividerBackgroundColor $SEQUENCE_BG_COLOR
skinparam SequenceDividerFontColor $BOUNDARY_COLOR
skinparam SequenceDividerBorderColor $BOUNDARY_COLOR

' VIA STYLE
' skinparam SequenceDelayFontColor green
<style>
sequenceDiagram {
  delay {
    FontColor $BOUNDARY_COLOR
  }
}
</style>
